"""add language to transcript_chunks

Revision ID: 0e9cdb9a4c4c
Revises: 8254fbf8e785
Create Date: 2026-09-12 09:18:40.888471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9cdb9a4c4c'
down_revision: Union[str, Sequence[str], None] = '8254fbf8e785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('FR', 'EN', name='languageenum', create_constraint=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.drop_column('language')
    # ### end Alembic commands ###
