"""initial schema

Revision ID: 4e1ab6dd2715
Revises: 
Create Date: 2026-08-19 17:49:39.210873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1ab6dd2715'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('church_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='statusenum', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('youtube_url', sa.String(length=255), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=True),
    sa.Column('requires_speaker_filter', sa.Boolean(), nullable=False),
    sa.Column('name_keywords', sa.JSON(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_pastor_follows',
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('is_explicit_preference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('visitor_id', 'pastor_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('speaker_match', sa.Boolean(), nullable=False),
    sa.Column('match_reason', sa.String(length=255), nullable=False),
    sa.Column('transcript_status', sa.Enum('PENDING', 'FETCHED', 'UNAVAILABLE', 'ERROR', name='transcriptstatusenum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_chunks')
    op.drop_table('videos')
    op.drop_table('visitor_pastor_follows')
    op.drop_table('channels')
    op.drop_table('books')
    op.drop_table('visitors')
    op.drop_table('pastors')
    # ### end Alembic commands ###
