"""add chunking status to videos

Revision ID: b262502958b0
Revises: 0e9cdb9a4c4c
Create Date: 2026-09-12 09:30:46.476840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b262502958b0'
down_revision: Union[str, Sequence[str], None] = '0e9cdb9a4c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'chunking_status',
            sa.Enum('PENDING', 'DONE', name='chunkingstatusenum', create_constraint=True),
            nullable=False,
            server_default='PENDING',
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('chunking_status')
    # ### end Alembic commands ###
