"""add new table for data pipeline

Revision ID: b711a43060d7
Revises: d5e9bc5e80d7
Create Date: 2026-09-23 10:39:15.732651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b711a43060d7'
down_revision: Union[str, Sequence[str], None] = 'd5e9bc5e80d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pastor_id', 'task_name', name='uq_pastor_task_lock')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_locks')
    # ### end Alembic commands ###
