"""add prayer_signals and human_contact_requests


Revision ID: bd6bd160853c
Revises: 4e1ab6dd2715
Create Date: 2026-09-01 11:08:55.487909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6bd160853c'
down_revision: Union[str, Sequence[str], None] = '4e1ab6dd2715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_contact_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('EMOTIONAL_SPIRITUAL', 'HOUSING', 'FINANCIAL', 'ADMINISTRATIVE', 'OTHER', name='humancontactrequestcategoryenum', create_constraint=True), nullable=False),
    sa.Column('contact_method', sa.Enum('EMAIL', 'PHONE', name='contactmethodenum', create_constraint=True), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CLOSED', name='humancontactrequeststatusenum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pastor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PRAYED', name='prayersignalstatusenum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['pastor_id'], ['pastors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Ajout de show_id + sa contrainte FK sur videos : nécessite le
    # "batch mode" sous SQLite, qui recrée la table au lieu d'un ALTER
    # direct (non supporté par SQLite pour les contraintes).
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_videos_show_id_shows', 'shows', ['show_id'], ['id'])
 
    # NOTE : les deux op.drop_constraint(...) générés automatiquement sur
    # 'statusenum' (pastors) et 'transcriptstatusenum' (videos) ont été
    # retirés — faux positif déjà rencontré lors de la migration initiale
    # (Alembic compare mal les contraintes CHECK d'Enum sur SQLite), et
    # de toute façon impossible à exécuter tel quel sur SQLite sans
    # batch mode. Ces contraintes n'ont pas changé, rien à faire ici.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_videos_show_id_shows', type_='foreignkey')
        batch_op.drop_column('show_id')
 
    op.drop_table('shows')
    op.drop_table('prayer_signals')
    op.drop_table('human_contact_requests')
    # ### end Alembic commands ###
