"""Add book_url in Pastor datatable

Revision ID: d5e9bc5e80d7
Revises: b262502958b0
Create Date: 2026-09-17 16:32:45.079346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e9bc5e80d7'
down_revision: Union[str, Sequence[str], None] = 'b262502958b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastors', sa.Column('book_shop_url', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastors', 'book_shop_url')
    # ### end Alembic commands ###
